name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: input
    id: feature-title
    attributes:
      label: Feature title
      description: A short, descriptive title for the feature
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation/problem
      description: Is your feature request related to a problem? Please describe.
    validations:
      required: true
  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed solution
      description: Describe the solution you'd like to see implemented.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: List any alternative solutions or features you've considered.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
